### ISSUE TITLE
1.19 TODO

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/FastAsyncWorldEdit#1780]
Blocking:

- [x] Port upstream changes
- [x] Adjust regen logic
- [x] Drop 1.18 and .1 from issue templates, changelog note required
  - [x] Add 1.19
