### ISSUE TITLE
#Roadmap

### ISSUE THREAD

**Issue by boy0001** [IntellectualSites/FastAsyncWorldEdit#99]
## Current Milestone
 - [ ] Finish merging translation changes @MattBDev (you mentioned you were working on stuff for this. Is that still the case?)
 - [ ] Chunk Lighting / lighting commands
 - [ ] More stateless Mask/Pattern (provide the extent)
 - [ ] VS pattern/masks
 - [ ] History list
 - [ ] [FRB import of disk history](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/126)
 - [ ] Shift operations down the pipeline (i.e. from EditSession -> IQueueExtent -> IChunk (if possible))
 - [ ] Anvil
 - [ ] CFI
 - [ ] [issues with `//restore`](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/96)

---- other optional changes
 - [ ] Lazy relighting (partial)
 - [ ] partial trimming of setBlocks in pool (instead of whole thing)
 - [ ] partial trimming of getBlocks in WorldChunkCache (instead of whole thing)
 - [ ] Reuse IGetBlocks
 - [ ] Reuse EditSession
 - [ ] Avoid relighting the same area every operation
 - [ ] Avoid relighting unloaded regions (can relight when the chunk is next loaded)
 - [ ] Use filters instead of Patterns
 - [ ] Use filters instead of Masks
 - [ ] Optimize patterns/masks with multiple or offset get/set (e.g. by implementing methods for adjacent blocks)
 - [ ] Integrated with Anvil (next roadmap)
 - [ ] Prevent unloading chunks if it's cached by WorldChunkCache (refactor from current chunk unload listener)
 - [ ] Low memory, switch over to SoftChunk
 - [ ] Benchmark create -> flush -> reuse of EditSession for single block changes
 - [ ] Avoid `BlockVector.at` inside pipeline

-----------------------------------------------------

## Future planned performance milestones
- [ ] Anvil @boy0001 (Anvil commands)
- [ ] implement Anvil EditSession (limited by history serialization) (~10x BPS improvement over NMS)
- [ ] Schematic cache (refactor from SchemVis) (~80x improvement to schematic loading)
- [ ] Implement unified Anvil history system (~40x BPS improvement over NMS)
- [ ] CFI editing for existing terrain (as a cache layer over Anvil) (~250x BPS improvement over NMS) 

#### (move these to whatever milestone it should be in)
Refactoring
- [ ] (Non critical) Remove use of BIT_MASK/BIT_OFFSET outside of BlockTypes

Logging
- [ ] Blockshub integration

Configuration
- [ ] move legacy config into fawe settings

Documentation:
- [ ] Document new regex pattern/mask usage `〈block type regex〉【〈property〉〈=｜!=｜>=｜<=〉〈value regex〉】`
- [ ] Document freebuild region restriction permissions (https://github.com/boy0001/FastAsyncWorldedit/wiki/Permissions)

Clipboards
- [ ] Legacy schematic importing NBT issues
- [ ] Structure blocks mutliple palettes (needs discussion with WE team)
- [ ] Clipboard on disk NBT/Entities
- [ ] Clipboard binding (instead of just serializing the command used, serialize the URI)
- [ ] Proper command to select/deselect clipboards

Minor optimizations:
- [ ] Optimize BlockTransformExtent caching
- [x] Use mask.optimize() everywhere
- [ ] Compressed clipboard on disk
- [ ] Disk cache for URI -> Clipboard (instead of loading it each time) 

CFI
- [ ] import existing worlds 
- [ ] on disk mode
- [x] Chunk visualization
- [ ] Map interaction

**Comment by MattBDev** [comment]
I was recently made aware there were FAWE builds of WorldGuard? Do we support those?

**Comment by mibby** [comment]
@MattBDev As far as I know, that was needed prior to the NVS branch since every plugin that relied on FAWE needed to be compiled with it as a dependency. However now FAWE 1.13 should be targeted with upstream WorldEdit compatibility in mind so plugins relying on WorldEdit don't need to be recompiled.

From my testing, WorldGuard dev 1838 functions fine with FastAsyncWorldEdit-Breaking dev 18.

**Comment by MattBDev** [comment]
I agree with @mibby that pre 1.13 schematic compatibility is needed for a stable release due to the large amount of schematic files for those versions.

**Comment by IronApollo** [comment]
@mibby if you're referring to the .schematic file type (also referred to as the MCEDITschematic format) not properly saving or importing NBT data, that's something that should be posted as an issue, then to this roadmap. In that issue, be sure to generate the debugpaste after you attempt to paste the target schematic.

**Comment by boy0001** [comment]
```
/br copypaste - does not paste the correct thing
/br sspl - says to click same spot again to apply, clicked same spot and nothing happens
/br layer - gives an error message "there was an error handling a FAWE command: [See console]
/br clipboard - doesn't let me execute because of max radius of 5, however am unable to set a lower radius as there is no option for it
/br butcher - tried to kill some mobs, but didn't work (nothing happened)
/br splatter - tried to execute the command, nothing happened



cuurrent commands WORKING:

/br sweep
/br erode
/br shatter
/br sphere
/br pull
/br stencil
/br recursive
/br spline
/br catenary
/br line
/br blendball
/br circle
/br rock
/br flatten
/br cylinder
/br surface
/br ex
/br gravity
/br cliff
/br smooth
/br scatter
these are all the brushes
```

**Comment by Tsoccerguy3** [comment]
Is anyone updating the TODO progress and posting a status of FAWE and FAV .

It makes it easy to look up bug status .

**Comment by MattBDev** [comment]
@boy0001 Please update this with your latest progress when you can.

**Comment by DankPrison** [comment]
@boy0001 Anvil Support when? It's been neglected for over 8 months now...

**Comment by dordsor21** [comment]
This is very outdated and not very relevant anymore. Going to close but someone else can open if they want. Also not the correct place for roadmaps anyway
